#!/usr/bin/env bash
# preflight.sh — derive THIS dev's verification-box inputs from your own environment
# and write terraform/terraform.tfvars. Nothing dev-specific is baked into the module;
# every personal value is read from where you already keep it. Read-only except for the
# gitignored tfvars it writes.
set -euo pipefail
cd "$(dirname "$0")"

PROJECT="$(gcloud config get-value project 2>/dev/null || true)"
IP="$(curl -fsSL --max-time 5 https://api.ipify.org 2>/dev/null || true)"
PUBKEY=""
for k in id_ed25519.pub id_rsa.pub; do
  if [ -f "$HOME/.ssh/$k" ]; then PUBKEY="$HOME/.ssh/$k"; break; fi
done

[ -n "$PROJECT" ] || { echo "No gcloud project set. Run: gcloud config set project <id>" >&2; exit 1; }
[ -n "$IP" ]      || { echo "Could not determine your public IP (api.ipify.org unreachable)." >&2; exit 1; }
[ -n "$PUBKEY" ]  || { echo "No SSH public key in ~/.ssh. Generate one: ssh-keygen -t ed25519" >&2; exit 1; }

cat > terraform/terraform.tfvars <<EOF
# Generated by preflight.sh from YOUR environment. Gitignored, local only.
project_id       = "$PROJECT"
ssh_pubkey_path  = "$PUBKEY"
allowed_ssh_cidr = "$IP/32"
cloud_init_path  = "../cloud-init/base.yaml"
EOF

echo "Wrote terraform/terraform.tfvars from your environment:"
echo "  project_id       = $PROJECT"
echo "  ssh_pubkey_path  = $PUBKEY"
echo "  allowed_ssh_cidr = $IP/32"
echo
echo "ADC auth still required: gcloud auth application-default login"
echo "Next: cd terraform && terraform init && terraform plan"
